open_weather:
  url: "https://api.openweathermap.org/data/2.5/weather"
  api_key: {{ env "OPEN_WEATHER_API_KEY" }}
  latitude: {{ env "LATITUDE" }}
  longitude: {{ env "LONGITUDE" }}

discord:
  webhook_url: {{ env "DISCORD_WEBHOOK_URL" }}
